name: Rocq

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu]

    steps:
    - name: Checkout Noir repo
      uses: actions/checkout@v4

    - name: Download Git submodules
      run: git submodule update --init --recursive

    - name: Run the Rocq tests
      uses: coq-community/docker-coq-action@v1
      with:
        custom_image: coqorg/coq:8.17-ocaml-4.14-flambda
        custom_script: |
          startGroup "Install dependencies"
            sudo ln -s `which python3` /usr/bin/python
            opam install -y --deps-only RocqOfNoir/rocq-of-noir.opam
          endGroup
          startGroup "Change permissions"
            sudo chown -R $(whoami) .
          endGroup
          startGroup "Convert to Rocq"
            python scripts/rocq_of_noir.py RocqOfNoir/base64/monomorphized_program.json >RocqOfNoir/base64/monomorphic.v
          endGroup
          startGroup "Check that the diff is empty (excluding submodules)"
            git -c color.ui=always diff --exit-code --ignore-submodules=dirty
          endGroup
          startGroup "Compile Rocq translations"
            cd RocqOfNoir
            make
            cd ..
          endGroup
